# Generated by Django 5.1.2 on 2024-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_description_remove_product_image_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hireDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
