# Generated by Django 5.1.2 on 2024-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_hiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hireDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
