# Generated by Django 5.1.2 on 2024-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_hiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('COO', 'COO'), ('Manager', 'MANAGER'), ('Supervisor', 'SUPERVISOR'), ('Associate', 'ASSOCIATE'), ('Admin', 'ADMIN'), ('Intern', 'INTERN')], max_length=30, null=True),
        ),
    ]
