# Generated by Django 5.1.2 on 2024-11-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
