# Generated by Django 5.1.2 on 2024-11-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Employee',
        ),
    ]
